/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
import { GlobalComponents } from 'vue'

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AddNodeModal: typeof import('./src/components/desktop/AddNodeModal.vue')['default']
    AppToolLayout: typeof import('./src/components/PageLayout/AppToolLayout.vue')['default']
    DateTimeHeader: typeof import('./src/components/desktop/DateTimeHeader.vue')['default']
    DesktopFolder: typeof import('./src/components/desktop/DesktopFolder.vue')['default']
    DesktopGrid: typeof import('@/desktop/layout/DesktopGrid.vue')['default']
    DesktopIcon: typeof import('./src/components/desktop/DesktopIcon.vue')['default']
    DetailDialog: typeof import('@/nested/plugin/components/DetailDialog.vue')['default']
    EmptyResult: typeof import('./src/components/Result/EmptyResult.vue')['default']
    InfoResult: typeof import('./src/components/Result/InfoResult.vue')['default']
    InstallDialog: typeof import('@/nested/plugin/components/InstallDialog.vue')['default']
    LoadingResult: typeof import('./src/components/Result/LoadingResult.vue')['default']
    NAvatar: typeof import('./src/components/native/NAvatar.vue')['default']
    NFileSelect: typeof import('./src/components/native/NFileSelect.vue')['default']
    PluginCard: typeof import('@/nested/plugin/components/PluginCard.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SearchBar: typeof import('./src/components/desktop/SearchBar.vue')['default']
    SubPageLayout: typeof import('./src/components/PageLayout/SubPageLayout.vue')['default']
    SubTitle: typeof import('./src/components/PageTitle/SubTitle.vue')['default']
    SuccessResult: typeof import('./src/components/Result/SuccessResult.vue')['default']
    TButton: typeof import('tdesign-vue-next')['Button']
    TInput: typeof import('tdesign-vue-next')['Input']
    TTooltip: typeof import('tdesign-vue-next')['Tooltip']
    UpgradeDialog: typeof import('@/nested/plugin/components/UpgradeDialog.vue')['default']
    WdCell: typeof import('./src/components/wod/wd-cell.vue')['default']
    WdCellGroup: typeof import('./src/components/wod/wd-cell-group.vue')['default']
  }
}

// For TSX support
declare global {
  const AddNodeModal: typeof import('./src/components/desktop/AddNodeModal.vue')['default']
  const AppToolLayout: typeof import('./src/components/PageLayout/AppToolLayout.vue')['default']
  const DateTimeHeader: typeof import('./src/components/desktop/DateTimeHeader.vue')['default']
  const DesktopFolder: typeof import('./src/components/desktop/DesktopFolder.vue')['default']
  const DesktopGrid: typeof import('@/desktop/layout/DesktopGrid.vue')['default']
  const DesktopIcon: typeof import('./src/components/desktop/DesktopIcon.vue')['default']
  const DetailDialog: typeof import('@/nested/plugin/components/DetailDialog.vue')['default']
  const EmptyResult: typeof import('./src/components/Result/EmptyResult.vue')['default']
  const InfoResult: typeof import('./src/components/Result/InfoResult.vue')['default']
  const InstallDialog: typeof import('@/nested/plugin/components/InstallDialog.vue')['default']
  const LoadingResult: typeof import('./src/components/Result/LoadingResult.vue')['default']
  const NAvatar: typeof import('./src/components/native/NAvatar.vue')['default']
  const NFileSelect: typeof import('./src/components/native/NFileSelect.vue')['default']
  const PluginCard: typeof import('@/nested/plugin/components/PluginCard.vue')['default']
  const RouterLink: typeof import('vue-router')['RouterLink']
  const RouterView: typeof import('vue-router')['RouterView']
  const SearchBar: typeof import('./src/components/desktop/SearchBar.vue')['default']
  const SubPageLayout: typeof import('./src/components/PageLayout/SubPageLayout.vue')['default']
  const SubTitle: typeof import('./src/components/PageTitle/SubTitle.vue')['default']
  const SuccessResult: typeof import('./src/components/Result/SuccessResult.vue')['default']
  const TButton: typeof import('tdesign-vue-next')['Button']
  const TInput: typeof import('tdesign-vue-next')['Input']
  const TTooltip: typeof import('tdesign-vue-next')['Tooltip']
  const UpgradeDialog: typeof import('@/nested/plugin/components/UpgradeDialog.vue')['default']
  const WdCell: typeof import('./src/components/wod/wd-cell.vue')['default']
  const WdCellGroup: typeof import('./src/components/wod/wd-cell-group.vue')['default']
}