/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
import { GlobalComponents } from 'vue'

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AddNodeModal: typeof import('./src/components/desktop/AddNodeModal.vue')['default']
    AppToolLayout: typeof import('./src/components/PageLayout/AppToolLayout.vue')['default']
    EmptyResult: typeof import('./src/components/Result/EmptyResult.vue')['default']
    FdDialog: typeof import('./src/components/wod/FdDialog.vue')['default']
    InfoResult: typeof import('./src/components/Result/InfoResult.vue')['default']
    LoadingResult: typeof import('./src/components/Result/LoadingResult.vue')['default']
    NAvatar: typeof import('./src/components/native/NAvatar.vue')['default']
    NFileSelect: typeof import('./src/components/native/NFileSelect.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SubPageLayout: typeof import('./src/components/PageLayout/SubPageLayout.vue')['default']
    SubTitle: typeof import('./src/components/PageTitle/SubTitle.vue')['default']
    SuccessResult: typeof import('./src/components/Result/SuccessResult.vue')['default']
    TAside: typeof import('tdesign-vue-next')['Aside']
    TAvatar: typeof import('tdesign-vue-next')['Avatar']
    TButton: typeof import('tdesign-vue-next')['Button']
    TContent: typeof import('tdesign-vue-next')['Content']
    TInput: typeof import('tdesign-vue-next')['Input']
    TInputNumber: typeof import('tdesign-vue-next')['InputNumber']
    TLayout: typeof import('tdesign-vue-next')['Layout']
    TLoading: typeof import('tdesign-vue-next')['Loading']
    TMenu: typeof import('tdesign-vue-next')['Menu']
    TMenuItem: typeof import('tdesign-vue-next')['MenuItem']
    TRadioButton: typeof import('tdesign-vue-next')['RadioButton']
    TRadioGroup: typeof import('tdesign-vue-next')['RadioGroup']
    TTextarea: typeof import('tdesign-vue-next')['Textarea']
    TTooltip: typeof import('tdesign-vue-next')['Tooltip']
    WdCell: typeof import('./src/components/wod/wd-cell.vue')['default']
    WdCellGroup: typeof import('./src/components/wod/wd-cell-group.vue')['default']
  }
}

// For TSX support
declare global {
  const AddNodeModal: typeof import('./src/components/desktop/AddNodeModal.vue')['default']
  const AppToolLayout: typeof import('./src/components/PageLayout/AppToolLayout.vue')['default']
  const EmptyResult: typeof import('./src/components/Result/EmptyResult.vue')['default']
  const FdDialog: typeof import('./src/components/wod/FdDialog.vue')['default']
  const InfoResult: typeof import('./src/components/Result/InfoResult.vue')['default']
  const LoadingResult: typeof import('./src/components/Result/LoadingResult.vue')['default']
  const NAvatar: typeof import('./src/components/native/NAvatar.vue')['default']
  const NFileSelect: typeof import('./src/components/native/NFileSelect.vue')['default']
  const RouterLink: typeof import('vue-router')['RouterLink']
  const RouterView: typeof import('vue-router')['RouterView']
  const SubPageLayout: typeof import('./src/components/PageLayout/SubPageLayout.vue')['default']
  const SubTitle: typeof import('./src/components/PageTitle/SubTitle.vue')['default']
  const SuccessResult: typeof import('./src/components/Result/SuccessResult.vue')['default']
  const TAside: typeof import('tdesign-vue-next')['Aside']
  const TAvatar: typeof import('tdesign-vue-next')['Avatar']
  const TButton: typeof import('tdesign-vue-next')['Button']
  const TContent: typeof import('tdesign-vue-next')['Content']
  const TInput: typeof import('tdesign-vue-next')['Input']
  const TInputNumber: typeof import('tdesign-vue-next')['InputNumber']
  const TLayout: typeof import('tdesign-vue-next')['Layout']
  const TLoading: typeof import('tdesign-vue-next')['Loading']
  const TMenu: typeof import('tdesign-vue-next')['Menu']
  const TMenuItem: typeof import('tdesign-vue-next')['MenuItem']
  const TRadioButton: typeof import('tdesign-vue-next')['RadioButton']
  const TRadioGroup: typeof import('tdesign-vue-next')['RadioGroup']
  const TTextarea: typeof import('tdesign-vue-next')['Textarea']
  const TTooltip: typeof import('tdesign-vue-next')['Tooltip']
  const WdCell: typeof import('./src/components/wod/wd-cell.vue')['default']
  const WdCellGroup: typeof import('./src/components/wod/wd-cell-group.vue')['default']
}